version: 2

# Build configuration for your Go binaries
builds:
  - id: default
    main: ./cmd/app # Path to your main Go file (adjust as needed)
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

# Docker image configuration
dockers:
  - goos: linux
    goarch:
      - amd64
      - arm64
    image_templates:
      - "myuser/myapp:latest"
      - "myuser/myapp:{{ .Tag }}"
    dockerfile: Dockerfile
    use: docker
    skip_push: false # Set to true if you don't want to push the images during development

# Archive configuration (e.g., tar.gz or zip)
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

# Release configuration (e.g., GitHub releases)
release:
  github:
    owner: myuser
    name: myrepo
  footer: |
    ---
    Released by [GoReleaser](https://goreleaser.com).

# Changelog generation
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
